source 'https://rubygems.org'
gem 'jekyll', '~> 2.1.1'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
gem 'guard'
gem 'guard-jekyll-plus'
gem 'guard-livereload'
